name: revenuepred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - statsmodels=0.14.0
  - pytorch=2.0.1
  - matplotlib=3.7.2
  - plotly=5.16.1
  - pip:
    - tensorflow==2.13.0
    - prophet==1.1.4
    - azure-storage-blob==12.17.0
    - azure-identity==1.13.0
    - azure-mgmt-datafactory==3.1.0
    - azure-mgmt-resource==23.0.1
    - azure-applicationinsights==0.1.1
    - streamlit==1.25.0
    - pyarrow==12.0.1
    - python-dotenv==1.0.0
    - pytest==7.4.0
    - black==23.7.0
    - flake8==6.1.0
    - isort==5.12.0
    - opencensus-ext-azure==1.1.9
    - opencensus-ext-logging==0.1.1
    - azure-monitor-opentelemetry==1.0.0 